---
title: "amountofcontent"
author: "Eleanor"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## R Markdown

## read tv shows and movies csv files

movies <- read.csv(file.choose())
head(movies)

tvshows <- read.csv(file.choose())
head(tvshows)

```

```{r}

## Display number of movies and shows on each streaming service

netflixshows <- table(tvshows$Netflix == 1)
hulushows <- table(tvshows$Hulu == 1)
primeshows <- table(tvshows$Prime.Video == 1)
disneyshows <- table(tvshows$Disney. == 1)

netflixmovies <- table(movies$Netflix == 1)
hulumovies <- table(movies$Hulu == 1)
primemovies <- table(movies$Prime.Video == 1)
disneymovies <- table(movies$Disney. == 1)
```
```{r}
## New data frame of number of movies
amtofmovies <- data.frame(matrix(ncol=4, nrow=0))
y <- c("Netflix", "Hulu", "Disney+", "Amazon Prime")
colnames(amtofmovies) <- y
amtofmovies <- structure(rbind(amtofmovies, c(3560, 903, 564, 12354)), .Names = names(amtofmovies))
amtofmovies <- data.frame(service=c("Netflix", "Hulu", "Disney+", "Amazon Prime"), numofmovies=c(3560, 903, 564, 12354))

## New data frame of number of tv shows
amtofshows <- data.frame(matrix(ncol=4, nrow=0))
y <- c("Netflix", "Hulu", "Disney+", "Amazon Prime")
colnames(amtofshows) <- y
amtofshows <- structure(rbind(amtofshows, c(1931, 1754, 180, 2144)), .Names = names(amtofshows))
amtofshows <- data.frame(service=c("Netflix", "Hulu", "Disney+", "Amazon Prime"), numofshows=c(1931, 1754, 180, 2144))
```

```{r}
## Create Bar Plots for each streaming service

library(ggplot2)

## Movies

ggplot(data = amtofmovies, aes(x=service, y=numofmovies)) + geom_bar(stat = "identity")
moviescontent <- ggplot(amtofmovies, aes(x=service, y=numofmovies, fill=service)) + geom_bar(stat="identity", color="white")
moviescontent+scale_fill_manual(values=c("#FFAF12", "#34558B", "#4EC5A5", "#D0393E"))+ggtitle("Amount of content per streaming service") +
  xlab("Streaming Service") + ylab("Number of movies")

## Shows

ggplot(data = amtofshows, aes(x=service, y=numofshows)) + geom_bar(stat = "identity")
showscontent <- ggplot(amtofshows, aes(x=service, y=numofshows, fill=service)) + geom_bar(stat="identity", color="white")
showscontent+scale_fill_manual(values=c("#FFAF12", "#34558B", "#4EC5A5", "#D0393E"))+ggtitle("Amount of content per streaming service") +
  xlab("Streaming Service") + ylab("Number of shows")
  
## Double Bar Plot comparing movies and shows

total <- merge(amtofmovies, amtofshows, by="service")
 
# create a dataset
streaming <- c(rep("Netflix" , 2) , rep("Hulu" , 2) , rep("Disney+" , 2) , rep("Amazon Prime" , 2) )
condition <- rep(c("movies", "shows") , 4)
value <- c(3560, 1931, 903, 1754, 564, 180, 12354, 2144)
data <- data.frame(streaming,condition,value)
 
# Grouped
ggplot(data, aes(fill=condition, y=value, x=streaming)) + 
    geom_bar(position="dodge", stat="identity") + scale_fill_manual(values=c("#b392ac", "#e8c2ca"))+ggtitle("Movies and Shows per streaming service") +
  xlab("Streaming Service") + ylab("Number of titles")

```
