---
title: "IMDb and Rotten Tomatoes"
output:
  html_document:
    keep_md: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```


## Import Data

```{r}
table <- read.csv("/Users/Luna/Desktop/Movie/the-avocados-movies/resources/MoviesOnStreamingPlatforms_updated.csv")

# convert rotten tomato column into numerical data
rotten_ch <- as.character(table$Rotten.Tomatoes)

rotten_ch <- strsplit(rotten_ch, split = "%")

rotten_temp <- numeric(0)

for (i in 1:16744) {
  if (length(rotten_ch[i]) == 0){
    rotten_temp <- c(rotten_temp, NA)
  } else {
    rotten_temp <- c(rotten_temp, rotten_ch[i])
  }
}

rotten_ch <- rotten_temp

rotten_ch <- as.numeric(rotten_ch) / 100


table$Rotten.Tomatoes <- rotten_ch
knitr::kable(head(table))
```

## Histogram of IMDb Rating and Rotten Tomatoes
```{r}
netflix <- table[table$Netflix == 1,]
mean(netflix$IMDb, na.rm = TRUE)


# hulu
hulu <- table[table$Hulu == 1,]
mean(hulu$IMDb, na.rm = TRUE)


# prime
prime <- table[table$Prime.Video == 1,]
mean(prime$IMDb, na.rm = TRUE)


# disney
disney <- table[table$Disney. == 1,]

mean(disney$IMDb, na.rm = TRUE)

par(mfrow = c(2, 2))
hist(netflix$IMDb)
abline(v = mean(netflix$IMDb, na.rm = TRUE), lty = 2, col = "red")
legend("topleft", c("Mean"), col = c("red"),
lty = c(2), inset = 0.05 )

hist(hulu$IMDb)
abline(v = mean(hulu$IMDb, na.rm = TRUE), lty = 2, col = "red")
legend("topleft", c("Mean"), col = c("red"),
lty = c(2), inset = 0.05 )

hist(prime$IMDb)
abline(v = mean(prime$IMDb, na.rm = TRUE), lty = 2, col = "red")
legend("topleft", c("Mean"), col = c("red"),
lty = c(2), inset = 0.05 )

hist(disney$IMDb)
abline(v = mean(disney$IMDb, na.rm = TRUE), lty = 2, col = "red")
legend("topleft", c("Mean"), col = c("red"),
lty = c(2), inset = 0.05 )
```




```{r}
hist(netflix$IMDb, main = 'IMDb Rating', xlab = 'IMDb',
     prob = FALSE, density = 20, col = "red",
     ylim = c(0, 2000), xlim=c(0, 10))
hist(hulu$IMDb, main = 'hulu', add = TRUE,
     prob = FALSE, density = 20, col = "blue",)
hist(prime$IMDb, main = 'prime', add = TRUE,
     prob = FALSE, density = 20, col = "#9FE2BF",)
hist(disney$IMDb, main = 'disney', add = TRUE,
     prob = FALSE, density = 20, col = "yellow",)

legend("topleft", c("Netflix", "Hulu", 'Prime', 'Disney+'), density = c(20, 20, 20, 20),
fill = c("red", "blue", "#9FE2BF", "yellow"), inset = 0.05)
```

```{r}

hist(netflix$Rotten.Tomatoes, main = 'Rotten Tomatoes', xlab = 'Rotten Tomatoes',
     prob = FALSE, density = 20, col = "red",
     ylim = c(0, 800))
hist(hulu$Rotten.Tomatoes, main = 'hulu', add = TRUE,
     prob = FALSE, density = 20, col = "blue",)
hist(prime$Rotten.Tomatoes, main = 'prime', add = TRUE,
     prob = FALSE, density = 20, col = "#9FE2BF",)
hist(disney$Rotten.Tomatoes, main = 'disney', add = TRUE,
     prob = FALSE, density = 20, col = "yellow",)

legend("topleft", c("Netflix", "Hulu", 'Prime', 'Disney+'), density = c(20, 20, 20, 20),
fill = c("red", "blue", "#9FE2BF", "yellow"), inset = 0.05)
```


## T-test on mean

```{r}
mean_imdb <- data.frame("Netflix" = mean(netflix$IMDb, na.rm = TRUE),
                        "Hulu" = mean(hulu$IMDb, na.rm = TRUE),
                        "Prime" = mean(prime$IMDb, na.rm = TRUE),
                        "Disney+" = mean(disney$IMDb, na.rm = TRUE))
mean_imdb
```


```{r}
netflix_hulu <- t.test(netflix$IMDb, hulu$IMDb, alternative = "two.sided", var.equal = FALSE)
netflix_prime <- t.test(netflix$IMDb, prime$IMDb, alternative = "two.sided", var.equal = FALSE)
netflix_disney <- t.test(netflix$IMDb, disney$IMDb, alternative = "two.sided", var.equal = FALSE)

hulu_prime <- t.test(hulu$IMDb, prime$IMDb, alternative = "two.sided", var.equal = FALSE)
hulu_disney <- t.test(hulu$IMDb, disney$IMDb, alternative = "two.sided", var.equal = FALSE)

prime_disney <- t.test(prime$IMDb, disney$IMDb, alternative = "two.sided", var.equal = FALSE)

t_test <- data.frame("Netflix" = c(NA, netflix_hulu$p.value, netflix_prime$p.value, netflix_disney$p.value), "Hulu" = c(NA, NA, hulu_prime$p.value, hulu_disney$p.value), "Prime" = c(NA, NA, NA, prime_disney$p.value), "Disney+" = c(NA, NA, NA, NA))
rownames(t_test) <- c("Netflix", "Hulu", "Prime", "Disney+")
t_test
```


## Boxplots of IMDb Rating

```{r}
library(ggplot2)
```


```{r}
# create imdb dataset
imbd <- data.frame("Platform" = c(), "IMDb" = c())
df_netflix <- data.frame("Platform" = "Netflix", "IMDb" = netflix$IMDb)
df_hulu <- data.frame("Platform" = "Hulu", "IMDb" = hulu$IMDb)
df_prime <- data.frame("Platform" = "Prime", "IMDb" = prime$IMDb)
df_disney <- data.frame("Platform" = "Disney+", "IMDb" = disney$IMDb)
imdb <- rbind(df_netflix, df_hulu, df_prime, df_disney)
```

```{r}
p1 <- ggplot(imdb, aes(x=Platform, y=IMDb)) + 
  geom_boxplot()
p1 <- p1 + ggtitle("IMDB of movies on four platforms")
```


```{r}
# action movies
action_movies <- data.frame()
for (i in 1:16744){
  movie_to_test <- table[i,]
  genre <- as.character(movie_to_test$Genres)
  genre <- unlist(strsplit(genre, split = ","))
  if (any("Action" == genre)){
    action_movies <- rbind(action_movies, movie_to_test)
  }
}


action_netflix <- table[action_movies$Netflix == 1,]
action_hulu <- table[action_movies$Hulu == 1,]
action_prime <- table[action_movies$Prime.Video == 1,]
action_disney <- table[action_movies$Disney. == 1,]

df_action_imdb <- data.frame("Platform" = c(), "IMDb" = c())
df_action_netflix <- data.frame("Platform" = "Netflix", "IMDb" = action_netflix$IMDb)
df_action_hulu <- data.frame("Platform" = "Hulu", "IMDb" = action_hulu$IMDb)
df_action_prime <- data.frame("Platform" = "Prime", "IMDb" = action_prime$IMDb)
df_action_disney <- data.frame("Platform" = "Disney+", "IMDb" = action_disney$IMDb)
df_action_imdb <- rbind(df_action_netflix, df_action_hulu, df_action_prime, df_action_disney)

p2 <- ggplot(df_action_imdb, aes(x=Platform, y=IMDb)) + 
  geom_boxplot()
p2 <- p2 + ggtitle("IMDB of Action Movies")
```

```{r}
# Sci-Fi movies
scifi_movies <- data.frame()
for (i in 1:16744){
  movie_to_test <- table[i,]
  genre <- as.character(movie_to_test$Genres)
  genre <- unlist(strsplit(genre, split = ","))
  if (any("Sci-Fi" == genre)){
    scifi_movies <- rbind(scifi_movies, movie_to_test)
  }
}


scifi_netflix <- table[scifi_movies$Netflix == 1,]
scifi_hulu <- table[scifi_movies$Hulu == 1,]
scifi_prime <- table[scifi_movies$Prime.Video == 1,]
scifi_disney <- table[scifi_movies$Disney. == 1,]

df_scifi_imdb <- data.frame("Platform" = c(), "IMDb" = c())
df_scifi_netflix <- data.frame("Platform" = "Netflix", "IMDb" = scifi_netflix$IMDb)
df_scifi_hulu <- data.frame("Platform" = "Hulu", "IMDb" = scifi_hulu$IMDb)
df_scifi_prime <- data.frame("Platform" = "Prime", "IMDb" = scifi_prime$IMDb)
df_scifi_disney <- data.frame("Platform" = "Disney+", "IMDb" = scifi_disney$IMDb)
df_scifi_imdb <- rbind(df_scifi_netflix, df_scifi_hulu, df_scifi_prime, df_scifi_disney)

p3 <- ggplot(df_scifi_imdb, aes(x=Platform, y=IMDb)) + 
  geom_boxplot()
p3 <- p3 + ggtitle("IMDB of Sci-Fi Movies")
```


```{r}
# Comedy movies
comedy_movies <- data.frame()
for (i in 1:16744){
  movie_to_test <- table[i,]
  genre <- as.character(movie_to_test$Genres)
  genre <- unlist(strsplit(genre, split = ","))
  if (any("Comedy" == genre)){
    comedy_movies <- rbind(scifi_movies, movie_to_test)
  }
}


comedy_netflix <- table[comedy_movies$Netflix == 1,]
comedy_hulu <- table[comedy_movies$Hulu == 1,]
comedy_prime <- table[comedy_movies$Prime.Video == 1,]
comedy_disney <- table[comedy_movies$Disney. == 1,]

df_comedy_imdb <- data.frame("Platform" = c(), "IMDb" = c())
df_comedy_netflix <- data.frame("Platform" = "Netflix", "IMDb" = comedy_netflix$IMDb)
df_comedy_hulu <- data.frame("Platform" = "Hulu", "IMDb" = comedy_hulu$IMDb)
df_comedy_prime <- data.frame("Platform" = "Prime", "IMDb" = comedy_prime$IMDb)
df_comedy_disney <- data.frame("Platform" = "Disney+", "IMDb" = comedy_disney$IMDb)
df_comedy_imdb <- rbind(df_comedy_netflix, df_comedy_hulu, df_comedy_prime, df_comedy_disney)

p4 <- ggplot(df_comedy_imdb, aes(x=Platform, y=IMDb)) + 
  geom_boxplot()
p4 <- p4 + ggtitle("IMDB of Comedy Movies")
```

```{r}
library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)
```

## Boxplots of Rotten Tomatoes

```{r}
rotten <- data.frame("Platform" = c(), "Rotten" = c())
df_netflix_rotten <- data.frame("Platform" = "Netflix", "Rotten" = netflix$Rotten.Tomatoes)
df_hulu_rotten <- data.frame("Platform" = "Hulu", "Rotten" = hulu$Rotten.Tomatoes)
df_prime_rotten <- data.frame("Platform" = "Prime", "Rotten" = prime$Rotten.Tomatoes)
df_disney_rotten <- data.frame("Platform" = "Disney+", "Rotten" = disney$Rotten.Tomatoes)
rotten <- rbind(df_netflix_rotten, df_hulu_rotten, df_prime_rotten, df_disney_rotten)

r1 <- ggplot(rotten, aes(x=Platform, y=Rotten)) + 
  geom_boxplot()
r1 <- r1 + ggtitle("Rotten Tomatoes on the four platforms")
```


```{r}
# action movies

df_action_rotten <- data.frame("Platform" = c(), "Rotten" = c())

df_action_netflix_rotten <- data.frame("Platform" = "Netflix", "Rotten" = action_netflix$Rotten.Tomatoes)
df_action_hulu_rotten <- data.frame("Platform" = "Hulu", "Rotten" = action_hulu$Rotten.Tomatoes)
df_action_prime_rotten <- data.frame("Platform" = "Prime", "Rotten" = action_prime$Rotten.Tomatoes)
df_action_disney_rotten <- data.frame("Platform" = "Disney+", "Rotten" = action_disney$Rotten.Tomatoes)

df_action_rotten <- rbind(df_action_netflix_rotten,
                          df_action_hulu_rotten,
                          df_action_prime_rotten,
                          df_action_disney_rotten)

r2 <- ggplot(df_action_rotten, aes(x=Platform, y=Rotten)) + 
  geom_boxplot()
r2 <- r2 + ggtitle("Rotten Tomatoes of Action Movies")
```

```{r}
# sci-fi movies

df_scifi_rotten <- data.frame("Platform" = c(), "Rotten" = c())

df_scifi_netflix_rotten <- data.frame("Platform" = "Netflix", "Rotten" = scifi_netflix$Rotten.Tomatoes)
df_scifi_hulu_rotten <- data.frame("Platform" = "Hulu", "Rotten" = scifi_hulu$Rotten.Tomatoes)
df_scifi_prime_rotten <- data.frame("Platform" = "Prime", "Rotten" = scifi_prime$Rotten.Tomatoes)
df_scifi_disney_rotten <- data.frame("Platform" = "Disney+", "Rotten" = scifi_disney$Rotten.Tomatoes)

df_scifi_rotten <- rbind(df_scifi_netflix_rotten,
                          df_scifi_hulu_rotten,
                          df_scifi_prime_rotten,
                          df_scifi_disney_rotten)

r3 <- ggplot(df_scifi_rotten, aes(x=Platform, y=Rotten)) + 
  geom_boxplot()
r3 <- r3 + ggtitle("Rotten Tomatoes of Sci-Fi Movies")
```


```{r}
# comedy movies

df_comedy_rotten <- data.frame("Platform" = c(), "Rotten" = c())

df_comedy_netflix_rotten <- data.frame("Platform" = "Netflix", "Rotten" = comedy_netflix$Rotten.Tomatoes)
df_comedy_hulu_rotten <- data.frame("Platform" = "Hulu", "Rotten" = comedy_hulu$Rotten.Tomatoes)
df_comedy_prime_rotten <- data.frame("Platform" = "Prime", "Rotten" = comedy_prime$Rotten.Tomatoes)
df_comedy_disney_rotten <- data.frame("Platform" = "Disney+", "Rotten" = comedy_disney$Rotten.Tomatoes)

df_comedy_rotten <- rbind(df_comedy_netflix_rotten,
                          df_comedy_hulu_rotten,
                          df_comedy_prime_rotten,
                          df_comedy_disney_rotten)

r4 <- ggplot(df_comedy_rotten, aes(x=Platform, y=Rotten)) + 
  geom_boxplot()
r4 <- r4 + ggtitle("Rotten Tomatoes of Comedy Movies")
```


```{r}
grid.arrange(r1, r2, r3, r4, nrow = 2, ncol = 2)
```

## Data on Movies above 8.0

```{r}
movie_above_eight <- table[(table$IMDb >= 8.0) & !is.na(table$IMDb), ]
netflix_eight <- movie_above_eight[movie_above_eight$Netflix == 1,]
hulu_eight <- movie_above_eight[movie_above_eight$Hulu == 1,]
prime_eight <- movie_above_eight[movie_above_eight$Prime.Video == 1,]
disney_eight <- movie_above_eight[movie_above_eight$Disney. == 1,]
nrow(netflix_eight)
nrow(hulu_eight)
nrow(prime_eight)
nrow(disney_eight)
nrow(movie_above_eight)
knitr::kable(head(movie_above_eight))
```

## Data on movies with imdb between 6 and 8

```{r}
movie_six_to_eight <- table[(table$IMDb >= 6.0) & (table$IMDb < 8.0) & !is.na(table$IMDb), ]
netflix_six_to_eight <- movie_six_to_eight[movie_six_to_eight$Netflix == 1,]
hulu_six_to_eight <- movie_six_to_eight[movie_six_to_eight$Hulu == 1,]
prime_six_to_eight <- movie_six_to_eight[movie_six_to_eight$Prime.Video == 1,]
disney_six_to_eight <- movie_six_to_eight[movie_six_to_eight$Disney. == 1,]

knitr::kable(head(movie_six_to_eight))
```



```{r}

venn <- data.frame("Netflix" = c(),
                   "Hulu" = c(),
                   "Prime" = c(),
                   "Disney+" = c(),
                   "Count" = c())

venn <- rbind(venn, c(0,0,0,0,0),
              c(1,0,0,0,0), c(0,1,0,0,0), c(0,0,1,0,0), c(0,0,0,1,0),
              c(1,1,0,0,0), c(1,0,1,0,0), c(1,0,0,1,0), c(0,1,1,0,0), c(0,1,0,1,0), c(0,0,1,1,0),
              c(1,1,1,0,0), c(1,1,0,1,0), c(1,0,1,1,0), c(0,1,1,1,0),
              c(1,1,1,1,0))
colnames(venn) <- c("Netflix", "Hulu", "Prime", "Disney+", "Count")
venn[1,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 0),])
venn[2,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 0),])
venn[3,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 0),])
venn[4,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 0),])
venn[5,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 1),])
venn[6,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 0),])
venn[7,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 0),])
venn[8,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 1),])
venn[9,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 0),])
venn[10,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 1),])
venn[11,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 1),])
venn[12,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 0),])
venn[13,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 0)
                  & (movie_above_eight$Disney. == 1),])
venn[14,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 0)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 1),])
venn[15,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 0)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 1),])
venn[16,5] <- nrow(movie_above_eight[(movie_above_eight$Netflix == 1)
                  & (movie_above_eight$Hulu == 1)
                  & (movie_above_eight$Prime.Video == 1)
                  & (movie_above_eight$Disney. == 1),])
venn <- venn[2:16,]
#venn
platforms <- c("Netflix", "Hulu", "Prime", "Disney+", "Netflix + Hulu", "Netflix + Prime", "Netflix + Disney+", "Hulu + Prime", "Hulu + Disney+", "Prime + Disney+", "Netflix + Hulu + Prime","Netflix + Hulu + Disney+", "Netflix + Prime + Disney+", "Hulu + Prime + Disney+", "All")
venn <- cbind(platforms, venn)
venn <- venn[1:14,]
```

## Pie Chart to show percent of good movies
```{r}

bp<- ggplot(venn[, c(1,6)], aes(x="", y=Count, fill=platforms))+
geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)
pie <- pie + ggtitle("Number of movies with IMDb above 8.0 on various platforms")
pie
```

## Bar Plots on count and percentage

```{r}
df_total <- data.frame("Platform" = c("Netflix", "Netflix", "Netflix", "Hulu", "Hulu", "Hulu", "Prime", "Prime", "Prime", "Disney+", "Disney+", "Disney+"),
                       "IMDb" = rep(c("Above 8.0", "6.0-8.0", "Below 6.0"), 4),
                       "Count" = c(nrow(netflix_eight), nrow(netflix_six_to_eight), nrow(netflix)-nrow(netflix_eight)-nrow(netflix_six_to_eight),
                                  nrow(hulu_eight), nrow(hulu_six_to_eight), nrow(hulu) - nrow(hulu_eight)-nrow(hulu_six_to_eight),
                                  nrow(prime_eight), nrow(prime_six_to_eight) ,nrow(prime)-nrow(prime_eight)-nrow(prime_six_to_eight),
                                  nrow(disney_eight), nrow(disney_six_to_eight) ,nrow(disney) - nrow(disney_eight)-nrow(disney_six_to_eight))
)

df_total <- cbind(df_total,
                  "Percent" = c(nrow(netflix_eight)/nrow(netflix), nrow(netflix_six_to_eight)/nrow(netflix), 1-nrow(netflix_eight)/nrow(netflix)-nrow(netflix_six_to_eight)/nrow(netflix),
                                        nrow(hulu_eight)/nrow(hulu), nrow(hulu_six_to_eight)/nrow(hulu), 1-nrow(hulu_eight)/nrow(hulu)-nrow(hulu_six_to_eight)/nrow(hulu),
                                        nrow(prime_eight)/nrow(prime), nrow(prime_six_to_eight)/nrow(prime), 1-nrow(prime_eight)/nrow(prime)-nrow(prime_six_to_eight)/nrow(prime),
                              nrow(disney_eight)/nrow(disney), nrow(disney_six_to_eight)/nrow(disney), 1-nrow(disney_eight)/nrow(disney)-nrow(disney_six_to_eight)/nrow(disney)))

df_total$Percent <- round(df_total$Percent, digits = 3)
# 
# df_total <- cbind(df_total, "percentpos" = c(nrow(netflix)+700, nrow(netflix) - nrow(netflix_eight),
#                                               nrow(hulu)+700, nrow(hulu) - nrow(hulu_eight),
#                                               nrow(prime)+700, nrow(prime) - nrow(prime_eight),
#                                               nrow(disney)+700, nrow(disney) - nrow(disney_eight) +100))

percent <- ggplot(data=df_total, aes(x=factor(Platform, levels = c("Netflix", "Hulu", "Prime", "Disney+")), y=Count, fill=factor(IMDb, levels = c("Above 8.0", "6.0-8.0", "Below 6.0")))) +
  geom_bar(stat="identity")+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
# percent <- percent + geom_text(aes(y=percentpos, label=Percent), vjust=1.6, 
#             color="black", size=3.5)
percent <- percent + ggtitle("Count of movies of different ratings")
percent <- percent + labs(fill='IMDb')
percent
```

```{r}
library(rlang)
library(highcharter) 
# Set highcharter options
options(highcharter.theme = hc_theme_smpl(tooltip = list(valueDecimals = 2)))
```


```{r}
hc <- df_total %>% 
  hchart(
    'column', hcaes(x = Platform, y = Count, group = factor(IMDb, levels = c("Above 8.0", "6.0-8.0", "Below 6.0"))),
    stacking = "normal"
    ) %>%
hc_colors(c("#0073C2FF", "#EFC000FF", "#008080")) %>% hc_yAxis(max = 12.5*1000) %>% hc_title(
    text = "Number of Movies by Platforms and IMDb",
    margin = 20,
    align = "center"
    )


hc_2 <- df_total %>% 
  hchart(
    'column', hcaes(x = Platform, y = Percent, group = factor(IMDb, levels = c("Above 8.0", "6.0-8.0", "Below 6.0"))),
    stacking = "normal"
    ) %>%
hc_colors(c("#0073C2FF", "#EFC000FF", "#008080")) %>% hc_yAxis(max = 1) %>% hc_title(
    text = "Percentage of Movies by Platforms and IMDb",
    margin = 20,
    align = "center"
    )

lst <- list(hc, hc_2)
htmltools::tagList(lst)
```

